api:
  maxJobs: 1
  maxTextLength: 6500
  maxTimeout: 10
  port: 5000
  version: v1
audio:
  allowedExtensions:
  - .wav
  - .mp3
  - .ogg
  - .flac
  default: ./Assets/Audios
colors:
- red
- green
- blue
- magenta
- black
- orange
- purple
- pink
- brown
- gray
- lightblue
- darkgreen
ffmpeg:
  applyNormalization: true
  audioBitrate: 256k
  audioCodec: libmp3lame
  audioFormat: mp3
  captionFont: ./Assets/Fonts/Barlow_Condensed/BarlowCondensed-Bold.ttf
  captionLineUsagePercentage: 50
  captionPosition: bottom
  captionPositionOffset: 15%
  captionTextBorderColor: blue
  captionTextBorderColorHighlighted: random
  captionTextBorderWidth: 2
  captionTextBorderWidthHighlighted: 13%
  captionTextColor: white
  captionTextColorHighlighted: white
  channels: 2
  fps: 30
  horizontalCaptionFontSize: 4.5%
  isSilentThreshold: 0.01
  normalizationFilter: loudnorm
  pixelFormat: yuv420p
  sampleRate: 44100
  verticalCaptionFontSize: 9.0%
  videoBitrate: 5000k
  videoCodec: libx264
  videoFormat: mp4
storePath: ./Jobs
tts:
  language: en-us
  sampleRate: 24000
  speechRate: 0.8
  voice: af_nova
verbose: true
video:
  allowedExtensions:
  - .mp4
  - .avi
  - .mov
  - .mkv
  availableQualities:
  - - 4K
    - - 3840
      - 2160
  - - Full HD
    - - 1920
      - 1080
  - - HD
    - - 1280
      - 720
  - - 480p
    - - 854
      - 480
  - - 360p
    - - 640
      - 360
  availableTypes:
  - Horizontal
  - Vertical
  default: ./Assets/Videos
  fps: 30
  maxLengthPerVideo: 10
  quality: 4K
  type: Horizontal
whisper:
  language: en
  modelName: turbo
